In [1]:
import pandas as pd

In [2]:
pp = pd.read_csv('cats.csv')
print(pp.to_string())

     Unnamed: 0               Breed  Age (Years) Weight (kg)          Color  Gender     ID
0             0        Egyptian Mau           12           7          White    Male  181.0
1             1       Scottish Fold           17           8  Tortoiseshell    Male  907.0
2             2              Sphynx            9           9         Orange    Male  732.0
3             3            Oriental            6           7           Gray  Female  464.0
4             4            Savannah           14           7  Tortoiseshell  Female  451.0
5             5            Oriental            1           6          Black    Male  613.0
6             6            Balinese           14           4           Blue  Female  856.0
7             7            Savannah           11           9            Red  Female   98.0
8             8            Munchkin            6           8          Brown  Female  348.0
9             9                Manx            2           8         Calico    Male  796.0
10           10        Russian Blue            6           5          Sable    Male  743.0
11           11         Cornish Rex           18           2            Red  Female  693.0
12           12             Persian            2           6          White  Female  655.0
13           13              Birman           16           4          Brown    Male  815.0
14           14             Ragdoll           16           2          Cream    Male  298.0
15           15           Chartreux            7           9        Bicolor    Male  118.0
16           16            Oriental           12           4            Red    Male  162.0
17           17             Ragdoll            3           6        Pointed  Female  597.0
18           18             Burmese            3           2         Calico    Male  500.0
19           19          Abyssinian           19           7  Tortoiseshell    Male  630.0
20           20              Sphynx           11           4  Tortoiseshell    Male  818.0
21           21                Manx           17           8          White  Female  507.0
22           22  American Shorthair            7           6          Cream  Female  970.0
23           23             Ragdoll            8           9         Calico    Male  112.0
24           24            Savannah           13           5           Gray    Male  372.0
25           25    Exotic Shorthair            1           8        Bicolor  Female  705.0
26           26            Munchkin            5           6            Red  Female  725.0
27           27                Manx           13           5          Tabby    Male  802.0
28           28           Chartreux            2           6        Pointed    Male  797.0
29           29            Oriental           18           4         Calico  Female  573.0
30           30      Turkish Angora            6           8         Calico    Male  658.0
31           31   British Shorthair           19           2          Sable  Female  251.0
32           32           Himalayan           18           4            Red    Male  158.0
33           33           Singapura           17           8          Black  Female  485.0
34           34    Norwegian Forest           19           2          Brown  Female   72.0
35           35           Tonkinese            8           2  Tortoiseshell  Female  212.0
36           36            Balinese            4           7  Tortoiseshell  Female  111.0
37           37              Bengal           14           7          White    Male  523.0
38           38    Exotic Shorthair           16           7          Black  Female  750.0
39           39           Himalayan           16           4          Cream    Male  553.0
40           40            Siberian           17           4        Pointed  Female  611.0
41           41          Abyssinian           10           3        Bicolor    Male  376.0
42           42           Singapura           16           6           Gray    Male  488.0
43           43           Devon Rex            3           7        Bicolor  Female  704.0
44           44    Exotic Shorthair           13           5  Tortoiseshell  Female  282.0
45           45           Chartreux            4           5          White    Male  228.0
46           46          Abyssinian           16           7            Red  Female  593.0
47           47              Ocicat           14           2           Gray  Female  634.0
48           48                Manx            7           2           Blue    Male  345.0
49           49        Russian Blue            3           2          Brown  Female  929.0
50           50  American Shorthair            8           6       Tricolor    Male  741.0
51           51            Oriental           10           3  Tortoiseshell    Male  874.0
52           52            Balinese            3           7          Brown    Male  901.0
53           53              Ocicat           15           2           Gray  Female  575.0
54           54             Siamese           18           9          Brown  Female  601.0
55           55        Russian Blue           18           6           Gray  Female  319.0
56           56           Tonkinese           12           4          Tabby    Male  863.0
57           57              Birman            3           7            Red  Female  415.0
58           58              Birman            4           5        Bicolor    Male  709.0
59           59            Oriental            1           2  Tortoiseshell  Female   30.0
60           60         Cornish Rex           11           3         Orange    Male  804.0
61           61    Norwegian Forest           17           5          Black  Female  110.0
62           62             Burmese            2           8  Tortoiseshell  Female  219.0
63           63              Sphynx            6           3  Tortoiseshell  Female   35.0
64           64       Scottish Fold            8           5       Tricolor    Male   75.0
65           65        Egyptian Mau            2           9           Gray    Male  178.0
66           66          Abyssinian            2           2       Tricolor    Male  501.0
67           67             Siamese           15           8          White  Female  917.0
68           68       Scottish Fold           18           9            Red    Male  991.0
69           69  American Shorthair           11           2           Blue    Male  847.0
70           70            Balinese            3           7          Cream  Female  342.0
71           71             Ragdoll            3           5        Pointed  Female  297.0
72           72           Himalayan            4           4       Tricolor  Female  511.0
73           73            Siberian            7           7          Cream    Male  567.0
74           74   British Shorthair           14           7            Red  Female   84.0
75           75       Scottish Fold            2           4  Tortoiseshell    Male  566.0
76           76          Abyssinian            5           2  Tortoiseshell    Male  370.0
77           77           Singapura            4           2         Orange  Female  935.0
78           78            Oriental           17           4           Gray  Female   81.0
79           79      Turkish Angora           19           9        Bicolor  Female  765.0
80           80            Balinese           14           9          Black  Female  422.0
81           81           Chartreux            5           8  Tortoiseshell    Male  481.0
82           82            Munchkin           18           8         Orange  Female  454.0
83           83           Chartreux           11           8          Black  Female  317.0
84           84            Savannah           18           3          Brown  Female  170.0
85           85        Russian Blue           15           5          Tabby    Male  587.0
86           86            Savannah            4           4          Black  Female  853.0
87           87           Chartreux           13           2        Pointed    Male  555.0
88           88        Russian Blue           19           7  Tortoiseshell  Female    0.0
89           89           Chartreux           16           8         Calico  Female  117.0
90           90  American Shorthair           17           5          Brown    Male  262.0
91           91           Tonkinese            9           7         Orange    Male  800.0
92           92         Cornish Rex           15           6           Blue    Male   60.0
93           93            Savannah           17           7           Blue    Male  328.0
94           94           Chartreux            6           2          Tabby    Male   93.0
95           95      Turkish Angora           15           8            Red    Male  179.0
96           96             Burmese            7           3        Bicolor    Male  322.0
97           97             Siamese            8           4          Brown  Female  515.0
98           98          Maine Coon            9           5           Blue  Female  590.0
99           99         Cornish Rex           11           6        Bicolor  Female  527.0
100         100              Ocicat            9           6          White    Male  826.0
101         101            Savannah            5           2          Black    Male  722.0
102         102  American Shorthair            7           8        Bicolor  Female   59.0
103         103    Norwegian Forest           18           2  Tortoiseshell  Female  718.0
104         104            Siberian           13           8        Pointed  Female  686.0
105         105             Burmese           14           5        Pointed    Male   15.0
106         106    Exotic Shorthair           14           6         Calico    Male  671.0
107         107       Scottish Fold           11           4          Black  Female  457.0
108         108  American Shorthair            5           6        Pointed  Female  377.0
109         109        Egyptian Mau            3           8          Brown    Male  651.0
110         110        Russian Blue            4           9       Tricolor  Female  626.0
111         111            Oriental           11           8       Tricolor    Male  668.0
112         112           Himalayan            5           7          Brown  Female  858.0
113         113  American Shorthair           15           8          Brown    Male  824.0
114         114    Exotic Shorthair           12           5           Gray    Male  898.0
115         115            Savannah            8           4          Black  Female  275.0
116         116          Abyssinian            2           4            Red  Female  617.0
117         117            Munchkin            8           5            Red  Female  473.0
118         118   British Shorthair            2           4          Tabby  Female  994.0
119         119                Manx           19           6          Cream  Female  289.0
120         120       Scottish Fold            8           2          Brown    Male  135.0
121         121      Turkish Angora           19           9          Brown    Male  411.0
122         122           Himalayan           13           6           Blue  Female  489.0
123         123           Chartreux            2           5            Red    Male  239.0
124         124    Norwegian Forest            2           4          White  Female  698.0
125         125             Burmese           13           6            Red  Female  610.0
126         126    Norwegian Forest           14           3            Red    Male  819.0
127         127             Siamese            2           8         Calico    Male  747.0
128         128  American Shorthair           19           6           Gray  Female  519.0
129         129        Russian Blue           11           7           Blue    Male  579.0
130         130         Cornish Rex           18           9        Pointed    Male  423.0
131         131          Maine Coon           19           3  Tortoiseshell  Female  931.0
132         132       Scottish Fold           11           6          Tabby    Male  311.0
133         133            Savannah            2           9          White    Male  767.0
134         134              Bengal           11           5  Tortoiseshell  Female   99.0
135         135  American Shorthair           10           9            Red  Female  971.0
136         136        Egyptian Mau           15           2          Tabby    Male  288.0
137         137              Bengal           18           5          Brown  Female  834.0
138         138            Munchkin            1           8           Gray    Male  426.0
139         139             Ragdoll            8           3          Cream    Male  133.0
140         140         Cornish Rex            9           9           Blue    Male  688.0
141         141  American Shorthair            7           4         Orange  Female  246.0
142         142       Scottish Fold           17           8          Sable    Male  558.0
143         143              Ocicat           11           5            Red  Female  408.0
144         144  American Shorthair            6           8        Bicolor  Female  143.0
145         145              Bengal            5           2          Tabby    Male  524.0
146         146       Scottish Fold            8           8          Sable    Male  650.0
147         147           Himalayan           16           8            Red    Male  546.0
148         148             Ragdoll            4           4        Pointed  Female  189.0
149         149   British Shorthair           18           4         Calico  Female  715.0
150         150          Abyssinian            5           9  Tortoiseshell  Female  138.0
151         151            Munchkin           12           9          Sable  Female  283.0
152         152           Tonkinese           19           5        Pointed    Male  543.0
153         153           Tonkinese           14           8          Sable    Male  813.0
154         154   British Shorthair            8           4        Pointed    Male  779.0
155         155          Maine Coon           18           7          Black    Male  335.0
156         156       Scottish Fold           17           2          Sable    Male  265.0
157         157             Siamese            6           2         Orange    Male  321.0
158         158             Siamese            4           6        Pointed    Male  980.0
159         159             Burmese           13           3        Pointed    Male   16.0
160         160            Balinese           13           4            Red    Male  905.0
161         161            Savannah            3           2        Pointed    Male  168.0
162         162          Abyssinian            9           3          Tabby    Male   21.0
163         163        Egyptian Mau           17           5          Sable  Female  968.0
164         164             Burmese           14           9        Pointed  Female  186.0
165         165              Ocicat           14           7           Gray    Male  754.0
166         166   British Shorthair           17           6          Cream  Female   20.0
167         167              Bengal           18           5          Brown  Female  436.0
168         168    Exotic Shorthair           11           3          White  Female  334.0
169         169             Burmese            8           3           Blue  Female  407.0
170         170             Burmese           18           4        Bicolor  Female   77.0
171         171   British Shorthair            3           6        Bicolor  Female  177.0
172         172            Oriental            7           2           Blue    Male  682.0
173         173                Manx            7           4        Pointed  Female  670.0
174         174             Ragdoll            2           5       Tricolor    Male   92.0
175         175            Oriental           10           3           Gray  Female  386.0
176         176             Siamese           18           8         Calico  Female  329.0
177         177           Himalayan           18           8       Tricolor  Female  896.0
178         178             Persian           12           4         Orange    Male  206.0
179         179            Munchkin           10           8         Calico  Female  944.0
180         180           Tonkinese           16           9         Orange  Female  256.0
181         181              Sphynx            3           7          Sable    Male  324.0
182         182  American Shorthair            2           8          Black    Male  388.0
183         183   British Shorthair            1           8        Pointed    Male  599.0
184         184  American Shorthair           11           8           Blue    Male  891.0
185         185            Oriental            7           3       Tricolor  Female  300.0
186         186         Cornish Rex            6           9        Pointed    Male   22.0
187         187            Savannah           12           3          Sable  Female   86.0
188         188       Scottish Fold            3           5          Cream    Male  490.0
189         189          Abyssinian            2           5          Tabby  Female  241.0
190         190             Siamese           19           6           Gray    Male  583.0
191         191              Ocicat            4           5            Red  Female  160.0
192         192   British Shorthair            3           5       Tricolor    Male   68.0
193         193   British Shorthair            9           7          Black    Male  479.0
194         194        Egyptian Mau           16           4          White  Female  462.0
195         195    Norwegian Forest           19           9  Tortoiseshell  Female    1.0
196         196    Exotic Shorthair            2           5          Black  Female  132.0
197         197            Savannah           18           5         Calico  Female  425.0
198         198          Abyssinian            4           5         Calico  Female  453.0
199         199             Ragdoll            7           4         Calico    Male  151.0
200         200        Egyptian Mau           10           6        Pointed  Female  440.0
201         201         Cornish Rex           12           9          Sable    Male  521.0
202         202           Singapura            8           3         Orange    Male  925.0
203         203    Norwegian Forest            7           9          Cream    Male  263.0
204         204            Munchkin           13           8       Tricolor    Male  641.0
205         205            Balinese           12           4         Orange    Male  973.0
206         206          Maine Coon           18           5          Tabby    Male  559.0
207         207              Sphynx           19           8           Blue    Male  271.0
208         208             Persian            1           4            Red    Male  413.0
209         209       Scottish Fold            2           9          Sable  Female  821.0
210         210             Ragdoll            3           5         Orange  Female  828.0
211         211              Birman            8           6           Gray  Female  197.0
212         212        Egyptian Mau           18           8          White  Female  701.0
213         213  American Shorthair           13           8          Black    Male   39.0
214         214    Exotic Shorthair            6           4         Calico  Female  993.0
215         215              Sphynx            8           3       Tricolor  Female  805.0
216         216          Maine Coon           18           2          Cream  Female  605.0
217         217       Scottish Fold            9           6          Sable    Male   96.0

In [3]:
pp = pd.read_csv('cats.csv')
pp.loc[98]

Unnamed: 0             98
Breed          Maine Coon
Age (Years)             9
Weight (kg)             5
Color                Blue
Gender             Female
ID                  590.0
Name: 98, dtype: object

In [4]:
import pandas as pd
data = {
    'Breed': ['Tabby'],
    'Age (Years)': [3],
    'Weight (kg)': [5],
    'Color': ['Orange'],
    'Gender': ['Male'],
    'ID': [420],
}
zuko = pd.DataFrame(data)

zuko.to_csv('cats.csv', mode='a', index=False, header=True)
pp=pd.read_csv('cats.csv')
pp.tail

<bound method NDFrame.tail of      Unnamed: 0          Breed  Age (Years) Weight (kg)          Color  \
0             0   Egyptian Mau           12           7          White
1             1  Scottish Fold           17           8  Tortoiseshell
2             2         Sphynx            9           9         Orange
3             3       Oriental            6           7           Gray
4             4       Savannah           14           7  Tortoiseshell
...         ...            ...          ...         ...            ...
1005      Tabby              3            5      Orange           Male
1006      Breed    Age (Years)  Weight (kg)       Color         Gender
1007      Tabby              3            5      Orange           Male
1008      Breed    Age (Years)  Weight (kg)       Color         Gender
1009      Tabby              3            5      Orange           Male

      Gender     ID
0       Male  181.0
1       Male  907.0
2       Male  732.0
3     Female  464.0
4     Female  451.0
...      ...    ...
1005     420    NaN
1006      ID    NaN
1007     420    NaN
1008      ID    NaN
1009     420    NaN

[1010 rows x 7 columns]>

In [9]:
pp['Weight (lbs)'] = pp['Weight (kg)'] * 2.205
pp.head()

TypeError: can't multiply sequence by non-int of type 'float'